export { EditorialColumns } from './components/PEditorialColumns'
export { EditorialSurface } from './components/PEditorialSurface'
export { useTextFlow } from './hooks/useTextFlow'
export { flowText } from './lib/flowText'
export { carveLineSlots, createLineSlotResolver, getCircleBlockedLineRangeForRow, pickWidestLineSlot } from './lib/lineSlots'

export type { EditorialPlacement, EditorialFigure } from './lib/editorialFigures'
export type { EditorialTrack } from './lib/editorialTracks'
export type { EditorialColumnsProps } from './components/PEditorialColumns'
export type { EditorialSurfaceProps } from './components/PEditorialSurface'
export type { UseTextFlowInput, UseTextFlowResult } from './hooks/useTextFlow'
export type { PositionedLine, TextFlowInput, TextFlowResult } from './lib/flowText'
export type { LineSlot } from './lib/lineSlots'
