export { useElementWidth } from './core/hooks/useElementWidth'
export { useMeasuredText } from './core/hooks/useMeasuredText'
export { usePreparedText } from './core/hooks/usePreparedText'
export { usePreparedSegments } from './core/hooks/usePreparedSegments'
export { usePretextLayout } from './core/hooks/usePretextLayout'
export { usePretextLines } from './core/hooks/usePretextLines'
export { useTruncatedText } from './core/hooks/useTruncatedText'
export { createPretextTypography } from './core/lib/typography'
export { PText } from './core/components/PText'

export type { ElementWidthResult } from './core/hooks/useElementWidth'
export type { UseMeasuredTextInput, UseMeasuredTextResult } from './core/hooks/useMeasuredText'
export type { PrepareOptions, UsePreparedTextInput, UsePreparedTextResult } from './core/hooks/usePreparedText'
export type { UsePreparedSegmentsInput, UsePreparedSegmentsResult } from './core/hooks/usePreparedSegments'
export type { UsePretextLayoutInput, UsePretextLayoutResult } from './core/hooks/usePretextLayout'
export type { UsePretextLinesInput, UsePretextLinesResult } from './core/hooks/usePretextLines'
export type { UseTruncatedTextInput, UseTruncatedTextResult } from './core/hooks/useTruncatedText'
export type { PretextTypography, PretextTypographyInput, PretextTypographyObjectInput, PretextTypographyShorthandInput } from './core/lib/typography'
export type { PTextProps, PTextMeasure, PTextTag } from './core/components/PText'
